version: '2'
services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - db-data:/var/lib/postgresql/data
  camunda:
    build:
      context: .
    image: journey-camunda
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    links:
      - db
    ports:
      - "8080:8080"
volumes:
  db-data:
